export const CART_PRODUCT_DETAILS_REQUEST = 'CART_PRODUCT_DETAILS_REQUEST';
export const CART_PRODUCT_DETAILS_SUCCESS = 'CART_PRODUCT_DETAILS_SUCCESS';
export const CART_PRODUCT_DETAILS_FAIL = 'CART_PRODUCT_DETAILS_FAIL';
export const CART_PRODUCT_DETAILS_RESET = 'CART_PRODUCT_DETAILS_RESET';


