export const CHECKOUT_BILLING_ADDRESS = 'CHECKOUT_BILLING_ADDRESS';
export const CHECKOUT_SHIPPING_ADDRESS = 'CHECKOUT_SHIPPING_ADDRESS';
export const CHECKOUT_PAYMENT_METHOD = 'CHECKOUT_PAYMENT_METHOD';
export const CHECKOUT_RESET = 'CHECKOUT_RESET';